name: deploy-auth

on:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

defaults:
  run:
    working-directory: 'packages/auth'
